########################################################################################################
########################################################################################################
#
#     Just run this file over and over
#
#
########################################################################################################
########################################################################################################

# Notes:

# https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html
# https://docs.aws.amazon.com/cli/latest/reference/codebuild/start-build.html


version: 0.1

env:
  variables:
    key1: "value1"
    key2: "value2"
phases:
  install:
    commands:
      # - sudo apt-get update
      - whoami
      - sam --version

      # - INSTALL HOMEBREW 
      # - true || sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      # - su -c (sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)" ) noboby

      # - brew tap aws/tap
      # - brew install aws-sam-cli
      
      # - command

  pre_build:
    commands:
      - pwd
      - ls -al 
      # - REGION=$(aws configure get region)
      - SAM_APP_STACK_NAME=$APP_STACK_NAME-app
      - cd sam-app/
      - ls -al
      - sam validate --template template.yaml --debug
      - SAM_APP_STACK_FINALIZER_PROJECT_NAME=$SAM_APP_STACK_NAME-Finalizer


  build:
    commands:
      - sam build --template template.yaml --debug
      - sam deploy --template template.yaml --stack-name $SAM_APP_STACK_NAME --region $AWS_DEFAULT_REGION --no-fail-on-empty-changeset --debug
      - aws codebuild start-build --project-name $SAM_APP_STACK_FINALIZER_PROJECT_NAME 


  post_build:
    commands:
      # - sam deploy --stack-name $SAM_APP_STACK_NAME --region $REGION --debug
      - echo ***** Final Deployment of logmydata application completed *****











