########################################################################################################
########################################################################################################
#
#     Just run this file over and over
#
#
########################################################################################################
########################################################################################################

# Notes:

# https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html
#  


version: 0.2

env:
  variables:
    key1: "value1"
    key2: "value2"
phases:
  install:
    commands:
      - echo no install necessary
      # - command

  pre_build:
    commands:
      - pwd
      - ls -al 
      - cd sam-app/
      - sam validate --debug


  build:
    commands:
      - echo "Here, we need to add tests to put an object in the production bucket so we can put an object in there or GET and object in there"
      # - aws ec2 describe-vpcs
      # - aws s3 ls
      # - command

  post_build:
    commands:
      - echo CodeBuild project completed on `date`
      # - command











